// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodleApplication.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoodleApplication.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260102170826_UpdateCascadeDeleteBehavior")]
    partial class UpdateCascadeDeleteBehavior
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Chats.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirstUserId")
                        .HasColumnType("integer")
                        .HasColumnName("first_user_id");

                    b.Property<int>("SecondUserId")
                        .HasColumnType("integer")
                        .HasColumnName("second_user_id");

                    b.HasKey("Id");

                    b.HasIndex("FirstUserId");

                    b.HasIndex("SecondUserId");

                    b.ToTable("chatrooms", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstUserId = 5,
                            SecondUserId = 2
                        },
                        new
                        {
                            Id = 2,
                            FirstUserId = 6,
                            SecondUserId = 3
                        },
                        new
                        {
                            Id = 3,
                            FirstUserId = 5,
                            SecondUserId = 6
                        },
                        new
                        {
                            Id = 4,
                            FirstUserId = 7,
                            SecondUserId = 4
                        });
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Chats.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_room_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("SenderId");

                    b.HasIndex("UserId");

                    b.ToTable("messages", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatRoomId = 1,
                            Content = "Poštovani profesore, imam pitanje vezano uz zadaću.",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 9, 10, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ChatRoomId = 1,
                            Content = "Naravno, slobodno pitajte.",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 9, 10, 14, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ChatRoomId = 1,
                            Content = "Može li se zadaća predati dan kasnije?",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 9, 10, 14, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ChatRoomId = 1,
                            Content = "Da, ali uz umanjenje bodova od 10%.",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 9, 10, 14, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            ChatRoomId = 2,
                            Content = "Profesorice, kada su konzultacije?",
                            SenderId = 6,
                            SentAt = new DateTime(2025, 9, 11, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            ChatRoomId = 2,
                            Content = "Konzultacije su utorkom od 12-14h.",
                            SenderId = 3,
                            SentAt = new DateTime(2025, 9, 11, 10, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            ChatRoomId = 3,
                            Content = "Hej, jesi riješio zadaću iz C#?",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 9, 12, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            ChatRoomId = 3,
                            Content = "Radim na tome, treći zadatak mi nije jasan.",
                            SenderId = 6,
                            SentAt = new DateTime(2025, 9, 12, 18, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            ChatRoomId = 3,
                            Content = "Mogu ti pomoći, javi se na Discordu.",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 9, 12, 18, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            ChatRoomId = 4,
                            Content = "Profesore, nedostaje mi materijal s prošlog predavanja.",
                            SenderId = 7,
                            SentAt = new DateTime(2025, 9, 13, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            ChatRoomId = 4,
                            Content = "Uploadat ću ga danas do kraja dana.",
                            SenderId = 4,
                            SentAt = new DateTime(2025, 9, 13, 9, 45, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Courses.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("professor_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("announcements", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Dobrodošli na kolegij Programiranje u C#! Prvi sat je u ponedjeljak.",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 2,
                            Title = "Dobrodošli na kolegij"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Prva zadaća je objavljena. Rok za predaju je za tjedan dana.",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 9, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 2,
                            Title = "Zadaća 1"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Molim vas instalirajte PostgreSQL prije sljedećeg predavanja.",
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 9, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 2,
                            Title = "Instalacija PostgreSQL"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Odaberite temu za završni projekt do kraja mjeseca.",
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 9, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 3,
                            Title = "Projekt - teme"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Prvi kolokvij je zakazan za 15. listopada.",
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 9, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 3,
                            Title = "Kolokvij 1"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Laboratorijske vježbe počinju sljedeći tjedan.",
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 9, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 4,
                            Title = "Laboratorijske vježbe"
                        });
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Courses.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("professor_id");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("courses", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Programiranje u C#",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "Baze podataka",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Web razvoj",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Algoritmi i strukture podataka",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Računalne mreže",
                            ProfessorId = 4
                        });
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Courses.CourseStudent", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("course_students", "public");

                    b.HasData(
                        new
                        {
                            UserId = 5,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2025, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 6,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2025, 9, 1, 11, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 7,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2025, 9, 2, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 5,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2025, 9, 1, 10, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 8,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2025, 9, 3, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 9,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2025, 9, 3, 15, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 6,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2025, 9, 2, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 7,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2025, 9, 2, 8, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 8,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2025, 9, 2, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 9,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2025, 9, 2, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 5,
                            CourseId = 4,
                            EnrolledAt = new DateTime(2025, 9, 4, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 6,
                            CourseId = 4,
                            EnrolledAt = new DateTime(2025, 9, 4, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 7,
                            CourseId = 5,
                            EnrolledAt = new DateTime(2025, 9, 5, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 8,
                            CourseId = 5,
                            EnrolledAt = new DateTime(2025, 9, 5, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 9,
                            CourseId = 5,
                            EnrolledAt = new DateTime(2025, 9, 5, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Courses.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("materials", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2025, 9, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            Name = "Uvod u C#",
                            Url = "https://moodle.com/materials/csharp-intro.pdf"
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(2025, 9, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            Name = "OOP koncepti",
                            Url = "https://moodle.com/materials/oop-concepts.pdf"
                        },
                        new
                        {
                            Id = 3,
                            AddedAt = new DateTime(2025, 9, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            Name = "LINQ tutorial",
                            Url = "https://moodle.com/materials/linq-tutorial.pdf"
                        },
                        new
                        {
                            Id = 4,
                            AddedAt = new DateTime(2025, 9, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 2,
                            Name = "SQL osnove",
                            Url = "https://moodle.com/materials/sql-basics.pdf"
                        },
                        new
                        {
                            Id = 5,
                            AddedAt = new DateTime(2025, 9, 9, 11, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 2,
                            Name = "Entity Framework Core",
                            Url = "https://moodle.com/materials/ef-core.pdf"
                        },
                        new
                        {
                            Id = 6,
                            AddedAt = new DateTime(2025, 9, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 3,
                            Name = "HTML & CSS",
                            Url = "https://moodle.com/materials/html-css.pdf"
                        },
                        new
                        {
                            Id = 7,
                            AddedAt = new DateTime(2025, 9, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 3,
                            Name = "JavaScript osnove",
                            Url = "https://moodle.com/materials/js-basics.pdf"
                        },
                        new
                        {
                            Id = 8,
                            AddedAt = new DateTime(2025, 9, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 4,
                            Name = "Složenost algoritama",
                            Url = "https://moodle.com/materials/algorithm-complexity.pdf"
                        },
                        new
                        {
                            Id = 9,
                            AddedAt = new DateTime(2025, 9, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 5,
                            Name = "TCP/IP protokoli",
                            Url = "https://moodle.com/materials/tcp-ip.pdf"
                        });
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(1980, 1, 15),
                            Email = "admin@moodle.com",
                            Name = "Admin User",
                            PasswordHash = "admin123",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateOnly(1975, 5, 20),
                            Email = "ivan.horvat@moodle.com",
                            Name = "Dr. Ivan Horvat",
                            PasswordHash = "prof123",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateOnly(1982, 8, 10),
                            Email = "ana.kovac@moodle.com",
                            Name = "Dr. Ana Kovač",
                            PasswordHash = "prof123",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateOnly(1978, 3, 25),
                            Email = "marko.babic@moodle.com",
                            Name = "Dr. Marko Babić",
                            PasswordHash = "prof123",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateOnly(2000, 4, 12),
                            Email = "petra.novak@student.moodle.com",
                            Name = "Petra Novak",
                            PasswordHash = "student123",
                            Role = 0
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateOnly(2001, 7, 8),
                            Email = "luka.juric@student.moodle.com",
                            Name = "Luka Jurić",
                            PasswordHash = "student123",
                            Role = 0
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateOnly(1999, 11, 30),
                            Email = "maja.peric@student.moodle.com",
                            Name = "Maja Perić",
                            PasswordHash = "student123",
                            Role = 0
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateOnly(2002, 2, 14),
                            Email = "tomislav.knezevic@student.moodle.com",
                            Name = "Tomislav Knežević",
                            PasswordHash = "student123",
                            Role = 0
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateOnly(2000, 9, 5),
                            Email = "sara.matic@student.moodle.com",
                            Name = "Sara Matić",
                            PasswordHash = "student123",
                            Role = 0
                        });
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Chats.ChatRoom", b =>
                {
                    b.HasOne("MoodleApplication.Domain.Entities.Users.User", "FirstUser")
                        .WithMany()
                        .HasForeignKey("FirstUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodleApplication.Domain.Entities.Users.User", "SecondUser")
                        .WithMany()
                        .HasForeignKey("SecondUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstUser");

                    b.Navigation("SecondUser");
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Chats.Message", b =>
                {
                    b.HasOne("MoodleApplication.Domain.Entities.Chats.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodleApplication.Domain.Entities.Users.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodleApplication.Domain.Entities.Users.User", null)
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("UserId");

                    b.Navigation("ChatRoom");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Courses.Announcement", b =>
                {
                    b.HasOne("MoodleApplication.Domain.Entities.Courses.Course", "Course")
                        .WithMany("Announcements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodleApplication.Domain.Entities.Users.User", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Courses.Course", b =>
                {
                    b.HasOne("MoodleApplication.Domain.Entities.Users.User", "Professor")
                        .WithMany("TeachingCourses")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Courses.CourseStudent", b =>
                {
                    b.HasOne("MoodleApplication.Domain.Entities.Courses.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodleApplication.Domain.Entities.Users.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Courses.Material", b =>
                {
                    b.HasOne("MoodleApplication.Domain.Entities.Courses.Course", "Course")
                        .WithMany("Materials")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Chats.ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Courses.Course", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Enrollments");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("MoodleApplication.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("TeachingCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
